### ISSUE TITLE
Item frame problem

### ISSUE THREAD

**Issue by C0sm0s-Chill** [Adventure-Terraria-Server-Project/HouseRegions-Plugin#22]
Item frame take items in hand when player click on ..

**Comment by Stealownz** [comment]
Item frames are like chests now, HouseRegions plugin only protects the item frame tile but does not protect the contents.
Our other Protector plugin: https://github.com/Adventure-Terraria-Server-Project/Protector-Plugin
plans to support protecting the contents of item frames but is current not yet implemented.
